# Generated by Django 6.0.6 on 2026-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packingitem',
            name='default_quantity',
        ),
        migrations.AddField(
            model_name='packingitem',
            name='always',
            field=models.BooleanField(default=False, help_text='Include this item on every trip, regardless of categories.'),
        ),
    ]
