# Generated by Django 6.0.6 on 2026-06-22 19:32

from django.db import migrations, models


def migrate_per_person_to_allocation(apps, schema_editor):
    PackingItem = apps.get_model('app', 'PackingItem')
    for item in PackingItem.objects.filter(per_person=True):
        item.packing_allocation = 'individual'
        item.save(update_fields=['packing_allocation'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_packingitem_default_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(
                choices=[('adult', 'Adult'), ('child', 'Child')],
                default='adult',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='packing_allocation',
            field=models.CharField(
                choices=[
                    ('individual', 'Individual'),
                    ('adults_children', 'Adults / children'),
                    ('shared', 'Shared'),
                ],
                default='shared',
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_per_person_to_allocation, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='packingitem',
            name='per_person',
        ),
    ]
