# Generated by Django 6.0.6 on 2026-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_packingitem_per_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='member_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('pet', 'Pet')], default='adult', max_length=10),
        ),
    ]
