# Generated by Django 6.0.6 on 2026-06-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_familymember_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='icon',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('child', 'Child'), ('dog', 'Dog')], default='man', max_length=10),
        ),
    ]
