# Generated by Django 6.0.6 on 2026-06-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_familymember_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingitem',
            name='weather',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('cold', 'Cold')], default='', help_text='When set, this item is only included on trips with matching weather.', max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_cold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_hot',
            field=models.BooleanField(default=False),
        ),
    ]
