from django.urls import path

from app.views.home import HomeView
from app.views.profile import ProfileView
from app.views.packing_crud import (
    PackingItemCreateView,
    PackingItemDeleteView,
    PackingItemListView,
    PackingItemUpdateView,
    SectionCreateView,
    SectionDeleteView,
    SectionListView,
    SectionUpdateView,
)
from app.views.reference_crud import (
    AccommodationCreateView,
    AccommodationDeleteView,
    AccommodationListView,
    AccommodationUpdateView,
    ActivityCreateView,
    ActivityDeleteView,
    ActivityListView,
    ActivityUpdateView,
    DestinationCreateView,
    DestinationDeleteView,
    DestinationListView,
    DestinationUpdateView,
    MemberCreateView,
    MemberDeleteView,
    MemberListView,
    MemberUpdateView,
)
from app.views.trips import (
    TripCreateView,
    TripDeleteView,
    TripListView,
    TripPackingListView,
    TripUpdateView,
)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('members/', MemberListView.as_view(), name='member_list'),
    path('members/new/', MemberCreateView.as_view(), name='member_create'),
    path('members/<int:pk>/edit/', MemberUpdateView.as_view(), name='member_update'),
    path('members/<int:pk>/delete/', MemberDeleteView.as_view(), name='member_delete'),
    path('destinations/', DestinationListView.as_view(), name='destination_list'),
    path('destinations/new/', DestinationCreateView.as_view(), name='destination_create'),
    path('destinations/<int:pk>/edit/', DestinationUpdateView.as_view(), name='destination_update'),
    path('destinations/<int:pk>/delete/', DestinationDeleteView.as_view(), name='destination_delete'),
    path('activities/', ActivityListView.as_view(), name='activity_list'),
    path('activities/new/', ActivityCreateView.as_view(), name='activity_create'),
    path('activities/<int:pk>/edit/', ActivityUpdateView.as_view(), name='activity_update'),
    path('activities/<int:pk>/delete/', ActivityDeleteView.as_view(), name='activity_delete'),
    path('accommodations/', AccommodationListView.as_view(), name='accommodation_list'),
    path('accommodations/new/', AccommodationCreateView.as_view(), name='accommodation_create'),
    path('accommodations/<int:pk>/edit/', AccommodationUpdateView.as_view(), name='accommodation_update'),
    path('accommodations/<int:pk>/delete/', AccommodationDeleteView.as_view(), name='accommodation_delete'),
    path('sections/', SectionListView.as_view(), name='section_list'),
    path('sections/new/', SectionCreateView.as_view(), name='section_create'),
    path('sections/<int:pk>/edit/', SectionUpdateView.as_view(), name='section_update'),
    path('sections/<int:pk>/delete/', SectionDeleteView.as_view(), name='section_delete'),
    path('items/', PackingItemListView.as_view(), name='item_list'),
    path('items/new/', PackingItemCreateView.as_view(), name='item_create'),
    path('items/<int:pk>/edit/', PackingItemUpdateView.as_view(), name='item_update'),
    path('items/<int:pk>/delete/', PackingItemDeleteView.as_view(), name='item_delete'),
    path('trips/', TripListView.as_view(), name='trip_list'),
    path('trips/new/', TripCreateView.as_view(), name='trip_create'),
    path('trips/<int:pk>/edit/', TripUpdateView.as_view(), name='trip_update'),
    path('trips/<int:pk>/delete/', TripDeleteView.as_view(), name='trip_delete'),
    path('trips/<int:pk>/packing-list/', TripPackingListView.as_view(), name='trip_packing_list'),
]
